name: SubmoduleBuild

on:
  workflow_call:
    
env:
  OutputDirectory: ${{ github.workspace}}/output
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@master
        with:
          submodules: true
          repository: AbyssMod/Abyss
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Build
        run: dotnet build -c Release --property:OutputPath=${{ env.OutputDirectory }}

      - name: Upload Nuget Package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.nupkg
          if-no-files-found: error
          retention-days: 7
          path: ${{ env.OutputDirectory }}/${{ github.event.repository.name }}*.nupkg

      - name: Upload Dll
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.dll
          if-no-files-found: error
          retention-days: 90 
          path: ${{ env.OutputDirectory }}/${{ github.event.repository.name }}.dll
          
      - name: Upload XML
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.xml
          if-no-files-found: warn
          retention-days: 7
          path: ${{ env.OutputDirectory }}/${{ github.event.repository.name }}.xml
  deploy:
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:

      - name: Download Nuget Files
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.nupkg
          path: ${{ env.OutputDirectory }}/${{ github.event.repository.name }}.nupkg
         
      - name: Download Dll Files
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.dll
          path: ${{ env.OutputDirectory }}/${{ github.event.repository.name }}.dll

      - name: Download Xml Files
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.xml
          path: ${{ env.OutputDirectory }}/${{ github.event.repository.name }}.xml
        continue-on-error: true
          
      # Publish all NuGet packages to NuGet.org
      # Use --skip-duplicate to prevent errors if a package with the same version already exists.
      # If you retry a failed workflow, already published packages will be skipped without error.
      - name: Publish NuGet package
        shell: pwsh
        run: dotnet nuget push ${{ env.OutputDirectory }}/${{ github.event.repository.name }}.nupkg --api-key "${{ secrets.NUGET_TOKEN }}" --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.OutputDirectory }}/${{ github.event.repository.name }}.dll
            ${{ env.OutputDirectory }}/${{ github.event.repository.name }}.xml
